### PR TITLE
Split out ApplicationManagement and related sections

### PR DESCRIPTION
**Pull request by anssiko**
Split ApplicationManagement interface and other parts of the Runtime spec relevant to privileged applications only into their own spec, see:

http://anssiko.github.io/runtime/index.html
http://anssiko.github.io/runtime/privileged.html

See also:

http://lists.w3.org/Archives/Public/public-sysapps/2013Jun/0005.html

Given there are relatively many commits in this PR, here's a short summary to ease the review:

The first 11 commits in this PR ("remove X section") are about taking index.html as a starting point for privileged.html and removing all sections that are _not_ specific to privileged applications (there's a typo in the first commit message, should be "use index.html as a starting point for privileged.html").

The remaining commits sans the last one are non-normative changes to make the extension spec (privileged.html) a valid stand-alone spec.

The last commit is about removing sections that were split into the extensions spec (privileged.html) from index.html.

### CODE REVIEW

**Comment by martap** [comment]
Can we add any link to "Privileged Applications Extensions" in "Runtime and Security Model for Web Applications"? Apart from that I like idea of splitting it up.

**Comment by jplyle** [comment]
I'm in favour of splitting these parts from the main specification.  I would like to see all APIs that are only accessible to 'privileged' applications to link directly to this extension.

**Comment by anssiko** [comment]
@martap Thanks for the suggestion. I've updated the PR, let me know if anssiko/runtime@e7ffb9f81dbd25e38fe5afbc2cd2dd134456e737 addresses your concern.

@jplyle Thanks for your review. Do you mean all APIs accessible to privileged applications only must normatively reference the Privileged Applications Extensions spec? If so, I agree with you.

**Comment by martap** [comment]
@anssiko :+1:  yes this link is fine. Thanks!

Can you also add one sentence in section "10. Permissions"? I would expect to find this information in Permissions in the first place so it seems to be natural to repeat there also. What do you think?

It could be something short like that i.e.:
"Privileged applications are described in separate specification: <a href="privileged.html">Privileged Applications Extensions</a>"

**Comment by jplyle** [comment]
@anssiko Yes, that's exactly what I mean.  Glad you agree.

**Comment by anssiko** [comment]
@martap I agree with you, so I added another note to the Permissions section, see anssiko/runtime@020f73f4c05eb1a43a622acaea37197eea0eaa0e. You can view both the notes in the context of the spec at http://anssiko.github.io/runtime/index.html. I made this a note for now to clearly highlight content that was split out. Let me know if this works for you.

**Comment by martap** [comment]
@anssiko :+1:  yes it looks super :) thanks!

**Comment by anssiko** [comment]
[Cleaning up old open PRs. The work on this spec ended in 2015: https://www.w3.org/TR/runtime/]

**Pull request closed without merging**
