### PR TITLE
Fix some small typos in the index.html file.

### PR DESCRIPTION
**Pull request by jplyle**
Hi Mounir / Ming Jin,

I don't know whether any changes are possible during the current phase of the specification process, but I spotted a few typos and thought you might appreciated them being fixed in the FPWD.

Thanks,

John

### CODE REVIEW

**Comment by ming-jin** [comment]
+1

**Comment by marcoscaceres** [comment]
These all look good to me. We should merge these in ASAP.

**Comment by mounirlamouri** [comment]
Could you by any chance update your pull request? I unfortunately can't merge it as-is.

**Comment by mounirlamouri** [comment]
I just merged a few PR from Christophe regarding typos so I guess part of this patch is no longer needed.

**Comment by jplyle** [comment]
Sure, you're the editor - if you think all the typos are addressed, that's fine.  I haven't gone through to check.

**Comment by marcoscaceres** [comment]
@jplyle be good to merge the upstream and check. That way we can still merge this and close.

**Comment by mounirlamouri** [comment]
I would bet some fixes from that patch still applies but the patch itself no longer applies so it needs to be updated so I can merge it.

**Comment by jplyle** [comment]
Ok, I'll do that when I get a chance... I'm on a different machine right now, but I'll try and do it today.

**Comment by jplyle** [comment]
Whitespace and merge conflicts (along with my ineptitude with a different merge tool) appear to have made a mess of this.  I'll have another go.

**Comment by jplyle** [comment]
I'd like to close this PR and use the alternative I've just issued - https://github.com/sysapps/runtime/pull/40 - thanks.

**Comment by mounirlamouri** [comment]
Just merged PR #40 so closing this.

**Pull request closed without merging**
